package io.github.erdsgfc.jforge.annotation;

/** SQL dialect — determines the SQL flavour generated by the annotation processor. */
public enum Dialect {

    /** PostgreSQL / H2 PostgreSQL compatibility mode. */
    POSTGRESQL,

    /** MySQL / MariaDB. */
    MYSQL;
}